#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Dec 29 10:15:12 IST 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto a474823dcd144881a1d6bc608361c727 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Test_p1_2_func_synth xil_defaultlib.Test_p1_2 -log elaborate.log"
xelab -wto a474823dcd144881a1d6bc608361c727 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Test_p1_2_func_synth xil_defaultlib.Test_p1_2 -log elaborate.log

