# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lab/JeevanS/processor-vivado/final_processor/processor/processor.srcs/sources_1/ip/instruction_block_module/instruction_block_module.xci
# IP: The module: 'instruction_block_module' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lab/JeevanS/processor-vivado/final_processor/processor/processor.srcs/sources_1/ip/instruction_block_module/instruction_block_module_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_block_module'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lab/JeevanS/processor-vivado/final_processor/processor/processor.srcs/sources_1/ip/instruction_block_module/instruction_block_module.xci
# IP: The module: 'instruction_block_module' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lab/JeevanS/processor-vivado/final_processor/processor/processor.srcs/sources_1/ip/instruction_block_module/instruction_block_module_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_block_module'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
